#!/bin/bash
### BEGIN INIT INFO
# Provides: pi-client
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Launch the pi client
# Description: Start the service that will pull from the serial port and push updates to the server REST API
### END INIT INFO


usage() {
    echo "----------------------------------------------"
    echo "Usage: pi-client (stop|start|status)"
    echo "----------------------------------------------"
    exit 2
}

if [ -z $1 ]; then
    usage
fi

case $1 in
        stop)
                kill $(ps -ef | grep pi_clien[t] | awk '{print $2}')
        ;;
        start)
                /usr/local/pi-client/bin/pi_client >> /var/log/pi-client/pi-client.log &
        ;;
        status)
                ps -ef | grep pi_clien[t]  &> /dev/null
                running=$?
                if [ $running -eq 1 ]
                then
                  echo 'pi-client is stopped'
                fi

                if [ $running -eq 0 ]
                then
                  echo 'pi-client is running'
                fi
        ;;
        *)
                usage
        ;;
esac

exit 0
